apiVersion: actions.github.m.upbound.io/v1alpha1
kind: EnvironmentSecret
metadata:
  annotations:
    meta.upbound.io/example-id: actions/v1alpha1/environmentsecret
  labels:
    testing.upbound.io/example-name: example_secret
  name: example-secret
  namespace: upbound-system
spec:
  forProvider:
    environmentSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    plaintextValueSecretRef:
      key: example-key
      name: example-secret
    secretName: example_secret_name
